// packages/feedback-widget/src/components/ui/card.tsx
import { type ComponentProps, splitProps, type ValidComponent } from "solid-js";
import { Dynamic } from "solid-js/web";

import { cn } from "../../lib/utils";

export type CardRender = ValidComponent;

export type CardPartProps = ComponentProps<"div"> & {
  /** Overrides the rendered element (tag name or component). */
  render?: CardRender;
  /** Allows rendering a card as a link (e.g. `render="a"`). */
  href?: string;
};

export type CardProps = CardPartProps & {
  size?: "sm" | "default";
};

// function renderCardPart(props: CardPartProps, baseClass: string, slot: string) {
//   const [local, others] = splitProps(props, ["class", "render"]);

//   return (
//     <Dynamic
//       class={cn(baseClass, local.class)}
//       component={local.render ?? "div"}
//       data-slot={slot}
//       {...others}
//     />
//   );
// }

export function Card(props: CardProps) {
  const [local, others] = splitProps(props, ["class", "render", "size"]);

  return (
    <Dynamic
      class={cn(
        "bg-card text-card-foreground relative flex flex-col rounded-2xl border shadow-xs/5 not-dark:bg-clip-padding before:pointer-events-none before:absolute before:inset-0 before:rounded-[calc(var(--radius-2xl)-1px)] before:shadow-[0_1px_--theme(--color-black/4%)] dark:before:shadow-[0_-1px_--theme(--color-white/6%)]",
        local.size === "sm" &&
          "rounded-xl before:rounded-[calc(var(--radius-xl)-1px)]",
        local.class
      )}
      component={local.render ?? "div"}
      data-slot="card"
      {...others}
    />
  );
}

// export function CardFrame(props: CardPartProps) {
//   return renderCardPart(
//     props,
//     "relative flex flex-col rounded-2xl border bg-card not-dark:bg-clip-padding text-card-foreground shadow-xs/5 [--clip-bottom:-1rem] [--clip-top:-1rem] before:pointer-events-none before:absolute before:inset-0 before:rounded-[calc(var(--radius-2xl)-1px)] before:bg-muted/72 before:shadow-[0_1px_--theme(--color-black/4%)] has-data-[slot=table-container]:overflow-hidden *:data-[slot=card]:-m-px *:data-[slot=table-container]:-m-px *:data-[slot=table-container]:w-[calc(100%+2px)] *:not-first:data-[slot=card]:rounded-t-xl *:not-last:data-[slot=card]:rounded-b-xl *:data-[slot=card]:bg-clip-padding *:data-[slot=card]:shadow-none *:data-[slot=card]:before:hidden *:not-first:data-[slot=card]:before:rounded-t-[calc(var(--radius-xl)-1px)] *:not-last:data-[slot=card]:before:rounded-b-[calc(var(--radius-xl)-1px)] dark:before:shadow-[0_-1px_--theme(--color-white/6%)] *:data-[slot=card]:[clip-path:inset(var(--clip-top)_1px_var(--clip-bottom)_1px_round_calc(var(--radius-2xl)-1px))] *:data-[slot=card]:last:[--clip-bottom:1px] *:data-[slot=card]:first:[--clip-top:1px]",
//     "card-frame"
//   );
// }

// export function CardFrameHeader(props: CardPartProps) {
//   return renderCardPart(
//     props,
//     "relative flex grid auto-rows-min grid-rows-[auto_auto] flex-col items-start gap-x-4 px-6 py-4 has-data-[slot=card-frame-action]:grid-cols-[1fr_auto]",
//     "card-frame-header"
//   );
// }

// export function CardFrameTitle(props: CardPartProps) {
//   return renderCardPart(
//     props,
//     "self-center font-semibold text-sm",
//     "card-frame-title"
//   );
// }

// export function CardFrameDescription(props: CardPartProps) {
//   return renderCardPart(
//     props,
//     "self-center text-muted-foreground text-sm",
//     "card-frame-description"
//   );
// }

// export function CardFrameAction(props: CardPartProps) {
//   return renderCardPart(
//     props,
//     "col-start-2 nth-3:row-span-2 nth-3:row-start-1 inline-flex self-center justify-self-end",
//     "card-frame-action"
//   );
// }

// export function CardFrameFooter(props: CardPartProps) {
//   return renderCardPart(props, "px-6 py-4", "card-frame-footer");
// }

// export function CardHeader(props: CardPartProps) {
//   return renderCardPart(
//     props,
//     "grid auto-rows-min grid-rows-[auto_auto] items-start gap-1.5 p-6 in-[[data-slot=card]:has(>[data-slot=card-panel])]:pb-4 has-data-[slot=card-action]:grid-cols-[1fr_auto]",
//     "card-header"
//   );
// }

// export function CardTitle(props: CardPartProps) {
//   return renderCardPart(
//     props,
//     "font-heading font-semibold text-lg leading-none",
//     "card-title"
//   );
// }

// export function CardDescription(props: CardPartProps) {
//   return renderCardPart(
//     props,
//     "text-muted-foreground text-sm",
//     "card-description"
//   );
// }

// export function CardAction(props: CardPartProps) {
//   return renderCardPart(
//     props,
//     "col-start-2 row-span-2 row-start-1 inline-flex self-start justify-self-end",
//     "card-action"
//   );
// }

// export function CardPanel(props: CardPartProps) {
//   return renderCardPart(
//     props,
//     "flex-1 p-6 in-[[data-slot=card]:has(>[data-slot=card-header]:not(.border-b))]:pt-0 in-[[data-slot=card]:has(>[data-slot=card-footer]:not(.border-t))]:pb-0",
//     "card-panel"
//   );
// }

// export function CardFooter(props: CardPartProps) {
//   return renderCardPart(
//     props,
//     "flex items-center p-6 in-[[data-slot=card]:has(>[data-slot=card-panel])]:pt-4",
//     "card-footer"
//   );
// }

// apps/web/src/dashboard/components/ui/card.tsx
import type * as React from "react";

import { cn } from "~/lib/utils";

function Card({
  className,
  size = "default",
  ...props
}: React.ComponentProps<"div"> & { size?: "default" | "sm" }) {
  return (
    <div
      className={cn(
        "group/card flex flex-col gap-6 overflow-hidden rounded-4xl bg-card py-6 text-card-foreground text-sm shadow-md ring-1 ring-foreground/5 has-[>img:first-child]:pt-0 data-[size=sm]:gap-4 data-[size=sm]:py-4 dark:ring-foreground/10 *:[img:first-child]:rounded-t-4xl *:[img:last-child]:rounded-b-4xl",
        className
      )}
      data-size={size}
      data-slot="card"
      {...props}
    />
  );
}

function CardHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      className={cn(
        "group/card-header @container/card-header grid auto-rows-min items-start gap-1.5 rounded-t-4xl px-6 has-data-[slot=card-action]:grid-cols-[1fr_auto] has-data-[slot=card-description]:grid-rows-[auto_auto] group-data-[size=sm]/card:px-4 [.border-b]:pb-6 group-data-[size=sm]/card:[.border-b]:pb-4",
        className
      )}
      data-slot="card-header"
      {...props}
    />
  );
}

function CardTitle({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      className={cn(
        "font-medium text-base leading-snug group-data-[size=sm]/card:text-sm",
        className
      )}
      data-slot="card-title"
      {...props}
    />
  );
}

function CardDescription({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      className={cn("text-muted-foreground text-sm", className)}
      data-slot="card-description"
      {...props}
    />
  );
}

function CardAction({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      className={cn(
        "col-start-2 row-span-2 row-start-1 self-start justify-self-end",
        className
      )}
      data-slot="card-action"
      {...props}
    />
  );
}

function CardContent({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      className={cn("px-6 group-data-[size=sm]/card:px-4", className)}
      data-slot="card-content"
      {...props}
    />
  );
}

function CardFooter({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      className={cn(
        "flex items-center rounded-b-4xl px-6 group-data-[size=sm]/card:px-4 [.border-t]:pt-6 group-data-[size=sm]/card:[.border-t]:pt-4",
        className
      )}
      data-slot="card-footer"
      {...props}
    />
  );
}

export {
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardAction,
  CardDescription,
  CardContent,
};
