// packages/public-board/src/app/public-board-app.svelte
<script lang="ts">
import { Router } from "sv-router";
import type { PublicBoardAppProps } from "./public-board-app";
import "./router";
import SiteProvider from "../providers/site-provider.svelte";

let { basePath = "", site }: PublicBoardAppProps = $props();
</script>

<SiteProvider {site}>
  <Router base={basePath} />
</SiteProvider>

// apps/public-feature-board/src/app/public-board-app.tsx
import type { TSite } from "@feeblo/domain/site/schema";
import { RouterProvider } from "@tanstack/react-router";
import {
  getContext,
  Provider,
} from "../integrations/tanstack-query/root-provider";
import { SiteProvider } from "../providers/site-provider";
import { router } from "./public-board-router";

export interface PublicBoardAppProps {
  readonly site: TSite;
}

export function PublicBoardApp({ site }: PublicBoardAppProps) {
  return (
    <Provider queryClient={getContext().queryClient}>
      <SiteProvider site={site}>
        <RouterProvider router={router} />
      </SiteProvider>
    </Provider>
  );
}
