// apps/web/src/feature-board/providers/site-provider.tsx
import type { Site } from "@feeblo/domain/site/schema";
import { createContext, type ReactNode, useContext } from "react";

const SiteContext = createContext<Site | null>(null);

export function SiteProvider({
  children,
  site,
}: {
  children: ReactNode;
  site: Site;
}) {
  return <SiteContext.Provider value={site}>{children}</SiteContext.Provider>;
}

export function useSite() {
  const site = useContext(SiteContext);

  if (!site) {
    throw new Error("Site not found");
  }

  return site;
}

// packages/public-board/src/providers/site-provider.svelte
<script lang="ts">
  import type { Site } from "@feeblo/domain/site/schema";
  import { setSiteContext } from "./site-provider";

  interface Props {
    children?: import("svelte").Snippet;
    site: Site;
  }

  let { children, site }: Props = $props();

  setSiteContext(site);
</script>

{@render children?.()}
