// packages/public-board/src/routes/roadmap-page.svelte
<script lang="ts">
  const ROADMAP_ITEMS = [
    {
      quarter: "Q2",
      title: "Public API For Board Embeds",
      notes: "Expose board cards for external widgets and status mirrors.",
    },
    {
      quarter: "Q3",
      title: "Roadmap Milestones",
      notes: "Group posts into milestone timelines and release trains.",
    },
    {
      quarter: "Q4",
      title: "Feedback Voting Rules",
      notes: "Configure one-vote and weighted-vote modes for organizations.",
    },
  ] as const;
</script>

<section class="space-y-3">
  {#each ROADMAP_ITEMS as item}
    <article class="rounded-xl border border-zinc-200 bg-zinc-50 p-4">
      <p class="text-xs text-zinc-500 uppercase tracking-wide">
        {item.quarter}
      </p>
      <h2 class="mt-1 font-medium text-lg text-zinc-900">{item.title}</h2>
      <p class="mt-2 text-sm text-zinc-600">{item.notes}</p>
    </article>
  {/each}
</section>

// apps/web/src/feature-board/routes/roadmap-page.tsx
import { Badge } from "~/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";

const ROADMAP_ITEMS = [
  {
    notes: "Expose board cards for external widgets and status mirrors.",
    quarter: "Q2",
    title: "Public API for board embeds",
  },
  {
    notes: "Group posts into milestone timelines and release trains.",
    quarter: "Q3",
    title: "Roadmap milestones",
  },
  {
    notes: "Configure one-vote and weighted-vote modes for organizations.",
    quarter: "Q4",
    title: "Feedback voting rules",
  },
] as const;

export function RoadmapPage() {
  return (
    <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
      <div className="space-y-3">
        <Badge variant="outline">Roadmap preview</Badge>
        <h1 className="font-semibold text-3xl tracking-tight">What is next</h1>
        <p className="max-w-2xl text-muted-foreground text-sm leading-6">
          Planned public-facing improvements and milestones for the feedback
          experience.
        </p>
      </div>

      <div className="mt-8 grid gap-4 md:grid-cols-3">
        {ROADMAP_ITEMS.map((item) => (
          <Card className="ring-1 ring-border/60" key={item.title}>
            <CardHeader className="space-y-3">
              <Badge variant="outline">{item.quarter}</Badge>
              <CardTitle>{item.title}</CardTitle>
            </CardHeader>
            <CardContent className="text-muted-foreground text-sm leading-6">
              {item.notes}
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
