// apps/web/src/feature-board/components/common/navbar.tsx
import { Link, useLocation } from "wouter";
import { buttonVariants } from "~/components/ui/button";
import { useSite } from "../../providers/site-provider";

export function Navbar() {
  const site = useSite();
  const [location] = useLocation();
  const pathname = location || "/";
  const isFeedbackRoute = pathname === "/" || pathname.startsWith("/p/");
  const isRoadmapRoute = pathname === "/roadmap";

  return (
    <header className="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/80">
      <div className="mx-auto flex min-h-16 max-w-7xl flex-col gap-3 px-4 py-3 sm:px-6 lg:flex-row lg:items-center lg:justify-between lg:px-8">
        <div className="min-w-0">
          <Link className="block min-w-0 font-medium text-sm" href="/">
            <span className="block truncate">{site.name}</span>
            <span className="block text-muted-foreground text-xs">
              Public feedback board
            </span>
          </Link>
        </div>

        <nav className="flex flex-wrap items-center gap-1">
          <Link
            className={buttonVariants({
              size: "sm",
              variant: isFeedbackRoute ? "default" : "ghost",
            })}
            href="/"
          >
            Feedback
          </Link>
          <Link
            className={buttonVariants({
              size: "sm",
              variant: isRoadmapRoute ? "default" : "ghost",
            })}
            href="/roadmap"
          >
            Roadmap
          </Link>
        </nav>
      </div>
    </header>
  );
}

// packages/public-board/src/components/common/navbar.svelte
<script lang="ts">
import { route } from "../../app/router";
import { buttonVariants } from "../ui/button";

const pathname = $derived(route.pathname);
const isFeedbackRoute = $derived(pathname === "/" || pathname.startsWith("/p/"));
const isRoadmapRoute = $derived(pathname === "/roadmap" || pathname.startsWith("/roadmap"));
</script>

<header class="border-b">
  <div class="mx-auto flex h-16 max-w-7xl items-center justify-between gap-4 px-4 md:px-6">
    <div class="flex items-center gap-8">
      <a class="font-medium" href="/">Feedback App</a>

      <div class="flex items-center gap-1">
        <a
          class={buttonVariants({
            variant: isFeedbackRoute ? "default" : "ghost",
            size: "sm",
          })}
          href="/"
        >
          Feedback
        </a>
        <a
          class={buttonVariants({
            variant: isRoadmapRoute ? "default" : "ghost",
            size: "sm",
          })}
          href="/roadmap"
        >
          Roadmap
        </a>
      </div>
    </div>
  </div>
</header>
